services:
  safety-ai-assistant:
    build:
      context: ./safety_ai_ssistant
    ports:
      - "8002:8002"
    environment:
      - OLLAMA_API_URL=http://100.69.25.25:11434/api/generate
      - OLLAMA_MODEL=llama3.1:latest
    networks:
      - genai-road-safety-network

networks:
  genai-road-safety-network:
    driver: bridge
